cc_binary(
  name = 'blockStreaming_doubleBuffer',
  srcs = [
    'blockStreaming_doubleBuffer.c',
  ],
  deps = [
    '//lz4/lib:lz4',
  ]
)

cc_binary(
  name = 'blockStreaming_lineByLine',
  srcs = [
    'blockStreaming_lineByLine.c',
  ],
  deps = [
    '//lz4/lib:lz4',
  ]
)

cc_binary(
  name = 'blockStreaming_ringBuffer',
  srcs = [
    'blockStreaming_ringBuffer.c',
  ],
  deps = [
    '//lz4/lib:lz4',
  ]
)

cc_binary(
  name = 'HCStreaming_ringBuffer',
  srcs = [
    'HCStreaming_ringBuffer.c',
  ],
  deps = [
    '//lz4/lib:lz4',
  ]
)

cc_binary(
  name = 'printVersion',
  srcs = [
    'printVersion.c',
  ],
  deps = [
    '//lz4/lib:lz4',
  ]
)

